### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by 506890493** [apache/doris-website#1122]
Path:/zh-CN/docs/3.0/db-connect/arrow-flight-sql-connect

hi , i encountered below issue, could help me check? 

17:03:55.384 [grpc-nio-worker-ELG-1-4] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x62f238b9 ] OUTBOUND RST_STREAM: streamId=3 errorCode=8
Exception in thread "main" java.sql.SQLException: Error while executing SQL "select * from information_schema.tables;": org.apache.arrow.flight.FlightRuntimeException: CANCELLED: Failed to read message.
	at org.apache.calcite.avatica.Helper.createException(Helper.java:56)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:164)
	at org.apache.calcite.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:228)
	at com.pengtao.generator.doris.ArrowFlghtConnectTesting.main(ArrowFlghtConnectTesting.java:18)
Caused by: java.lang.RuntimeException: org.apache.arrow.flight.FlightRuntimeException: CANCELLED: Failed to read message.
	at org.apache.calcite.avatica.Helper.wrap(Helper.java:37)
	at org.apache.arrow.driver.jdbc.utils.FlightEndpointDataQueue.next(FlightEndpointDataQueue.java:112)
	at org.apache.arrow.driver.jdbc.utils.FlightEndpointDataQueue.next(FlightEndpointDataQueue.java:148)
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.getNextEndpointStream(ArrowFlightJdbcFlightStreamResultSet.java:260)
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.loadNewFlightStream(ArrowFlightJdbcFlightStreamResultSet.java:131)
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.populateData(ArrowFlightJdbcFlightStreamResultSet.java:146)
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.execute(ArrowFlightJdbcFlightStreamResultSet.java:138)
	at org.apache.calcite.avatica.AvaticaConnection$1.execute(AvaticaConnection.java:669)
	at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.prepareAndExecute(ArrowFlightMetaImpl.java:205)
	at org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:677)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:157)
	... 2 more

**Comment by KassieZ** [comment]
Thank you for the feedback, will update this issue to Engineer ASAP, also you can go to [Doris forum](https://ask.selectdb.com/tags/2.1) , there are engineer answer question and help you troubleshooting.

**Comment by xinyiZzz** [comment]
Hi @506890493 

看下 fe/log/fe.log 中有没有具体报错
